[package]
name = "bevy-open-world"
description = "Various crates for open world rendering in Bevy"
repository = "https://github.com/evroon/bevy-open-world"
readme = "README.md"
version = "0.1.0"
edition = "2024"
authors = ["evroon"]
rust-version = "1.89.0"
license = "MIT"
keywords = ["bevy", "serialization", "gamedev", "savegame", "plugin"]
categories = ["game-development"]
publish = false

[workspace]
members = ["crates/*"]

[features]
dev = ["bevy/dynamic_linking"]

[workspace.dependencies]
bevy = { version = "0.17.2", features=["file_watcher", "jpeg", "bevy_mesh"]}
bevy_panorbit_camera = "0.28.0"
bevy_egui = "0.37.1"
wayland-sys = { version="0.31.7", features = ["dlopen"] }
big_space = {version="0.11.0"}

[dependencies]
bevy = { workspace = true }
wayland-sys = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }
bevy_panorbit_camera = { workspace = true }
bevy_egui = { workspace = true }
wayland-sys = { workspace = true }
big_space = {version ="0.11.0", features=["camera"]}
turborand = "0.10.1"

bevy-where-was-i = { path = "crates/bevy-where-was-i" }
bevy-fly-camera = { path = "crates/bevy-fly-camera" }
bevy-volumetric-clouds = { path = "crates/bevy-volumetric-clouds" }
bevy-terrain = { path = "crates/bevy-terrain" }
