[package]
name = "bevy-earth"
description = "A plugin for Bevy that renders the earth"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["bevy_mesh"] }

[dev-dependencies]
bevy = { workspace = true }
