[package]
name = "bevy-cesium"
description = "A plugin for Bevy that renders Cesium 2d tiles"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["bevy_mesh"] }

[dev-dependencies]
bevy = { workspace = true }
