[package]
name = "bevy-terrain"
description = "A plugin for Bevy that renders quadtree terrain"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["bevy_mesh"] }
big_space = "0.12.0"
noise = "0.9.0"

[dev-dependencies]
bevy = { workspace = true }
